import { allCountries } from "src/utils/countries-languages/countriesLangs";

export const newsDataIo_countries = {
    "af": { name: "Afghanistan", code: "af" },
    "al": { name: "Albania", code: "al" },
    "dz": { name: "Algeria", code: "dz" },
    "ao": { name: "Angola", code: "ao" },
    "ar": { name: "Argentina", code: "ar" },
    "au": { name: "Australia", code: "au" },
    "at": { name: "Austria", code: "at" },
    "az": { name: "Azerbaijan", code: "az" },
    "bh": { name: "Bahrain", code: "bh" },
    "bd": { name: "Bangladesh", code: "bd" },
    "bb": { name: "Barbados", code: "bb" },
    "by": { name: "Belarus", code: "by" },
    "be": { name: "Belgium", code: "be" },
    "bm": { name: "Bermuda", code: "bm" },
    "bt": { name: "Bhutan", code: "bt" },
    "bo": { name: "Bolivia", code: "bo" },
    "ba": { name: "Bosnia And Herzegovina", code: "ba" },
    "br": { name: "Brazil", code: "br" },
    "bn": { name: "Brunei", code: "bn" },
    "bg": { name: "Bulgaria", code: "bg" },
    "bf": { name: "Burkina fasco", code: "bf" },
    "kh": { name: "Cambodia", code: "kh" },
    "cm": { name: "Cameroon", code: "cm" },
    "ca": { name: "Canada", code: "ca" },
    "cv": { name: "Cape Verde", code: "cv" },
    "ky": { name: "Cayman Islands", code: "ky" },
    "cl": { name: "Chile", code: "cl" },
    "cn": { name: "China", code: "cn" },
    "co": { name: "Colombia", code: "co" },
    "km": { name: "Comoros", code: "km" },
    "cr": { name: "Costa Rica", code: "cr" },
    "ci": { name: "Côte d'Ivoire", code: "ci" },
    "hr": { name: "Croatia", code: "hr" },
    "cu": { name: "Cuba", code: "cu" },
    "cy": { name: "Cyprus", code: "cy" },
    "cz": { name: "Czech republic", code: "cz" },
    "dk": { name: "Denmark", code: "dk" },
    "dj": { name: "Djibouti", code: "dj" },
    "dm": { name: "Dominica", code: "dm" },
    "do": { name: "Dominican republic", code: "do" },
    "cd": { name: "DR Congo", code: "cd" },
    "ec": { name: "Ecuador", code: "ec" },
    "eg": { name: "Egypt", code: "eg" },
    "sv": { name: "El Salvador", code: "sv" },
    "ee": { name: "Estonia", code: "ee" },
    "et": { name: "Ethiopia", code: "et" },
    "fj": { name: "Fiji", code: "fj" },
    "fi": { name: "Finland", code: "fi" },
    "fr": { name: "France", code: "fr" },
    "pf": { name: "French polynesia", code: "pf" },
    "ga": { name: "Gabon", code: "ga" },
    "ge": { name: "Georgia", code: "ge" },
    "de": { name: "Germany", code: "de" },
    "gh": { name: "Ghana", code: "gh" },
    "gr": { name: "Greece", code: "gr" },
    "gt": { name: "Guatemala", code: "gt" },
    "gn": { name: "Guinea", code: "gn" },
    "ht": { name: "Haiti", code: "ht" },
    "hn": { name: "Honduras", code: "hn" },
    "hk": { name: "Hong kong", code: "hk" },
    "hu": { name: "Hungary", code: "hu" },
    "is": { name: "Iceland", code: "is" },
    "in": { name: "India", code: "in" },
    "id": { name: "Indonesia", code: "id" },
    "iq": { name: "Iraq", code: "iq" },
    "ie": { name: "Ireland", code: "ie" },
    "il": { name: "Israel", code: "il" },
    "it": { name: "Italy", code: "it" },
    "jm": { name: "Jamaica", code: "jm" },
    "jp": { name: "Japan", code: "jp" },
    "jo": { name: "Jordan", code: "jo" },
    "kz": { name: "Kazakhstan", code: "kz" },
    "ke": { name: "Kenya", code: "ke" },
    "kw": { name: "Kuwait", code: "kw" },
    "kg": { name: "Kyrgyzstan", code: "kg" },
    "lv": { name: "Latvia", code: "lv" },
    "lb": { name: "Lebanon", code: "lb" },
    "ly": { name: "Libya", code: "ly" },
    "lt": { name: "Lithuania", code: "lt" },
    "lu": { name: "Luxembourg", code: "lu" },
    "mo": { name: "Macau", code: "mo" },
    "mk": { name: "Macedonia", code: "mk" },
    "mg": { name: "Madagascar", code: "mg" },
    "mw": { name: "Malawi", code: "mw" },
    "my": { name: "Malaysia", code: "my" },
    "mv": { name: "Maldives", code: "mv" },
    "ml": { name: "Mali", code: "ml" },
    "mt": { name: "Malta", code: "mt" },
    "mr": { name: "Mauritania", code: "mr" },
    "mx": { name: "Mexico", code: "mx" },
    "md": { name: "Moldova", code: "md" },
    "mn": { name: "Mongolia", code: "mn" },
    "me": { name: "Montenegro", code: "me" },
    "ma": { name: "Morocco", code: "ma" },
    "mz": { name: "Mozambique", code: "mz" },
    "mm": { name: "Myanmar", code: "mm" },
    "na": { name: "Namibia", code: "na" },
    "np": { name: "Nepal", code: "np" },
    "nl": { name: "Netherland", code: "nl" },
    "nz": { name: "New zealand", code: "nz" },
    "ne": { name: "Niger", code: "ne" },
    "ng": { name: "Nigeria", code: "ng" },
    "kp": { name: "North korea", code: "kp" },
    "no": { name: "Norway", code: "no" },
    "om": { name: "Oman", code: "om" },
    "pk": { name: "Pakistan", code: "pk" },
    "pa": { name: "Panama", code: "pa" },
    "py": { name: "Paraguay", code: "py" },
    "pe": { name: "Peru", code: "pe" },
    "ph": { name: "Philippines", code: "ph" },
    "pl": { name: "Poland", code: "pl" },
    "pt": { name: "Portugal", code: "pt" },
    "pr": { name: "Puerto rico", code: "pr" },
    "ro": { name: "Romania", code: "ro" },
    "ru": { name: "Russia", code: "ru" },
    "rw": { name: "Rwanda", code: "rw" },
    "ws": { name: "Samoa", code: "ws" },
    "sm": { name: "San Marino", code: "sm" },
    "sa": { name: "Saudi arabia", code: "sa" },
    "sn": { name: "Senegal", code: "sn" },
    "rs": { name: "Serbia", code: "rs" },
    "sg": { name: "Singapore", code: "sg" },
    "sk": { name: "Slovakia", code: "sk" },
    "si": { name: "Slovenia", code: "si" },
    "sb": { name: "Solomon Islands", code: "sb" },
    "so": { name: "Somalia", code: "so" },
    "za": { name: "South africa", code: "za" },
    "kr": { name: "South korea", code: "kr" },
    "es": { name: "Spain", code: "es" },
    "lk": { name: "Sri Lanka", code: "lk" },
    "sd": { name: "Sudan", code: "sd" },
    "se": { name: "Sweden", code: "se" },
    "ch": { name: "Switzerland", code: "ch" },
    "sy": { name: "Syria", code: "sy" },
    "tw": { name: "Taiwan", code: "tw" },
    "tj": { name: "Tajikistan", code: "tj" },
    "tz": { name: "Tanzania", code: "tz" },
    "th": { name: "Thailand", code: "th" },
    "to": { name: "Tonga", code: "to" },
    "tn": { name: "Tunisia", code: "tn" },
    "tr": { name: "Turkey", code: "tr" },
    "tm": { name: "Turkmenistan", code: "tm" },
    "ug": { name: "Uganda", code: "ug" },
    "ua": { name: "Ukraine", code: "ua" },
    "ae": { name: "United arab emirates", code: "ae" },
    "gb": { name: "United kingdom", code: "gb" },
    "us": { name: "United states of america", code: "us" },
    "uy": { name: "Uruguay", code: "uy" },
    "uz": { name: "Uzbekistan", code: "uz" },
    "ve": { name: "Venezuela", code: "ve" },
    "vi": { name: "Vietnam", code: "vi" },
    "ye": { name: "Yemen", code: "ye" },
    "zm": { name: "Zambia", code: "zm" },
    "zw": { name: "Zimbabwe", code: "zw" },
}

export const newsDataIo_categories = {
    "business": "business",
    "crime": "crime",
    "domestic": "domestic",
    "education": "education",
    "entertainment": "entertainment",
    "environment": "environment",
    "food": "food",
    "health": "health",
    "other": "other",
    "politics": "politics",
    "science": "science",
    "sports": "sports",
    "technology": "technology",
    "top": "top",
    "tourism": "tourism",
    "world": "world",
}